apiVersion: types.kubefed.k8s.io/v1beta1
kind: FederatedService
metadata:
  name: identity-public
  namespace: {{ .Values.namespaces.public.name }}
spec:
  template:
    spec:
      type: ExternalName
      externalName: {{ .Values.domain.private.name }}
      ports:
      - name: http
        port: 80
      - name: https
        port: 443
  placement:
    clusters:
    - name: {{ .Values.context.public.name }}
---
apiVersion: types.kubefed.k8s.io/v1beta1
kind: FederatedService
metadata:
  name: ordering-public
  namespace: {{ .Values.namespaces.public.name }}
spec:
  template:
    spec:
      type: ExternalName
      externalName: {{ .Values.domain.private.name }}
      ports:
      - name: http
        port: 80
      - name: https
        port: 443
  placement:
    clusters:
    - name: {{ .Values.context.public.name }}
---
apiVersion: types.kubefed.k8s.io/v1beta1
kind: FederatedService
metadata:
  name: ocelotapigw-ws-public
  namespace: {{ .Values.namespaces.public.name }}
spec:
  template:
    spec:
      type: ExternalName
      externalName: {{ .Values.domain.private.name }}
      ports:
      - name: http
        port: 80
      - name: https
        port: 443
  placement:
    clusters:
    - name: {{ .Values.context.public.name }}
