apiVersion: types.kubefed.k8s.io/v1beta1
kind: FederatedIngress
metadata:
  name: ingress-public
  namespace: {{ .Values.namespaces.public.name }}
spec:
  template:
    metadata:
      annotations:
        kubernetes.io/ingress.class: "nginx"    
    spec:
      tls:
      - hosts:
        - {{ .Values.domain.public.name }}
        secretName: {{ .Values.domain.public.tlsSecret }}
      rules:
      - host: {{ .Values.domain.public.name }}
        http:
          paths:
          - path: /identity
            backend:
              serviceName: identity-public
              servicePort: 80
          - path: /webmvc
            backend:
              serviceName: webmvc
              servicePort: 80
          - path: /webstatus
            backend:
              serviceName: webstatus
              servicePort: 80
          - path: /webshoppingapigw 
            backend:
              serviceName: ocelotapigw-ws
              servicePort: 80          
          - path: /webshoppingapigw/api/v1/o/orders
            backend:
              serviceName: ocelotapigw-ws-public
              servicePort: 80
          - path: /webmarketingapigw
            backend:
              serviceName: ocelotapigw-wm
              servicePort: 80
          - path: /mobilemarketingapigw
            backend:
              serviceName: ocelotapigw-mm
              servicePort: 80                    
          - path: /mobileshoppingapigw
            backend:
              serviceName: ocelotapigw-ms
              servicePort: 80          
          - path: /webshoppingagg
            backend:
              serviceName: webshoppingagg
              servicePort: 80
          - path: /mobileshoppingagg
            backend:
              serviceName: mobileshoppingagg
              servicePort: 80
          - path: /payment-api
            backend:
              serviceName: payment-public
              servicePort: 80                      
          - path: /
            backend:
              serviceName: webspa
              servicePort: 80
  placement:
    clusters:
    - name: {{ .Values.context.public.name }}
---
apiVersion: types.kubefed.k8s.io/v1beta1
kind: FederatedIngress
metadata:
  name: ingress-private
  namespace: {{ .Values.namespaces.private.name }}
spec:
  template:
    metadata:
      annotations:
        kubernetes.io/ingress.class: "nginx"    
        certmanager.k8s.io/issuer: "letsencrypt-prod"
        certmanager.k8s.io/acme-challenge-type: http01
    spec:
      tls:
      - hosts:
        - {{ .Values.domain.private.name }}
        secretName: {{ .Values.domain.private.tlsSecret }}
      rules:
      - host: {{ .Values.domain.private.name }}
        http:
          paths:
          - path: /identity
            backend:
              serviceName: identity
              servicePort: 80
          - path: /webmvc
            backend:
              serviceName: webmvc-private
              servicePort: 80
          - path: /webstatus
            backend:
              serviceName: webstatus-private
              servicePort: 80
          - path: /webshoppingapigw 
            backend:
              serviceName: ocelotapigw-ws
              servicePort: 80          
          - path: /webmarketingapigw
            backend:
              serviceName: ocelotapigw-wm
              servicePort: 80
          - path: /mobilemarketingapigw
            backend:
              serviceName: ocelotapigw-mm
              servicePort: 80                    
          - path: /mobileshoppingapigw
            backend:
              serviceName: ocelotapigw-ms
              servicePort: 80          
          - path: /webshoppingagg
            backend:
              serviceName: webshoppingagg-private
              servicePort: 80
          - path: /mobileshoppingagg
            backend:
              serviceName: mobileshoppingagg-private
              servicePort: 80
          - path: /payment-api
            backend:
              serviceName: payment
              servicePort: 80                      
          - path: /
            backend:
              serviceName: webspa-private
              servicePort: 80
      - host: {{ .Values.domain.public.name }}
        http:
          paths:
          - path: /identity
            backend:
              serviceName: identity
              servicePort: 80
          - path: /webmvc
            backend:
              serviceName: webmvc-private
              servicePort: 80
          - path: /webstatus
            backend:
              serviceName: webstatus-private
              servicePort: 80
          - path: /webshoppingapigw 
            backend:
              serviceName: ocelotapigw-ws
              servicePort: 80          
          - path: /webmarketingapigw
            backend:
              serviceName: ocelotapigw-wm
              servicePort: 80
          - path: /mobilemarketingapigw
            backend:
              serviceName: ocelotapigw-mm
              servicePort: 80                    
          - path: /mobileshoppingapigw
            backend:
              serviceName: ocelotapigw-ms
              servicePort: 80          
          - path: /webshoppingagg
            backend:
              serviceName: webshoppingagg-private
              servicePort: 80
          - path: /mobileshoppingagg
            backend:
              serviceName: mobileshoppingagg-private
              servicePort: 80
          - path: /payment-api
            backend:
              serviceName: payment
              servicePort: 80                      
          - path: /
            backend:
              serviceName: webspa-private
              servicePort: 80
  placement:
    clusters:
    - name: {{ .Values.context.private.name }}
